### ISSUE TITLE
Add context preservation to assembly template

### ISSUE THREAD

**Issue by pbokoc** [redhat-documentation/modular-docs#54] opened 2018-06-07 14:23 UTC
The current assembly template is missing a way to preserve the parent context. Therefore, if you use the current template and set a context for an assembly as the template guides you to, any subsequent non-assembly includes will inherit the assembly's context, even if they're not in that same assembly. For example, if your master file has these includes:

~~~
master.adoc
├── assembly_foo.adoc
├── assembly_bar.adoc
└── reference_foo.adoc
~~~

The first assembly sets its context, and so does the 2nd, so the 1st assembly's context ends as it should because it's overwritten by the 2nd. However, modules don't set their own context (that's the point), and so `reference_foo.adoc` inherits context from `assembly_bar.adoc`, which we don't want because it makes it potentially very difficult to determine how to link to it from elsewhere.

The way to avoid this is to save the parent context into another attribute before setting the assembly's internal context, and then reset it back using the other attribute at the end of the assembly. So the structure should look like this:

~~~asciidoc
:parent-context: {context}
//Saves the context of the parent to another variable
[id='assembly-title-{context}]
//Sets the assembly ID - still with the parent's context
= Assembly title
:context: assembly-context
//Sets context for anything included inside this assembly

Assembly intro

include::modules/foo.adoc[leveloffset=+1]
include::modules/bar.adoc[leveloffset=+1]

:context: {parent-context}
//Resets the context to what it was before the assembly's inner context was defined, so it doesn't "spill over" to any other parts of the title
~~~

**Comment by VladimirSlavik** [comment] 2018-06-11 10:17
See also @mrksu Marek's pull request for the very same: https://github.com/redhat-documentation/modular-docs/pull/52

**Comment by ritz303** [comment] 2018-06-18 19:08
Closing this issue, because PR #52 has been merged into the master branch.

**Closed by ritz303** 2018-06-18 19:08 UTC

**Comment by mrksu** [comment] 2018-06-18 19:49
There's another, related thing that I should mention. Suppose we have this structure:

```
master.adoc
├── assembly-a
│   ├── assembly-a1
│   └── assembly-a2
└── assembly-b
```

In this case, even if all assemblies use the `parent-context` attribute, the trouble is that assemblies `a1` and `a2` overwrite the value of `parent-context` that was saved in `assembly-a`. Then, `assembly-b` receives `assembly-a2` as context instead of the context that is set in `master.adoc`.

So in effect, the ID of `assembly-a` might be `assembly-a_book-name`, but `assembly-b` gets the `assembly-b_assembly-a2` ID instead of `assembly-b_book-name`.

The way to solve it is for the `parent-context` attribute to have a unique name in each assembly. In `assembly-a`, for example, there could be a `parent-context-of-assembly-a` attribute instead of just `parent-context`, which gets overwritten.

I know this is confusing and difficult to explain, but the issue is there nevertheless. I'm not sure if we want to solve it at all or solve it this way. If so, my script for generating files from module and assembly templates  handles it automatically.
